# -*- coding: utf-8 -*-
"""
studio.tests.test_utils
~~~~~~~~~~~~~~~~~~~~~~~~

Shared test utilities and helpers for NCE Studio's test suite.

Usage:
    bench --site your-site.localhost run-tests --app studio

    # Run a specific module
    bench --site your-site.localhost run-tests --app studio --module nce_module

    # Run tests for a specific DocType
    bench --site your-site.localhost run-tests --app studio --doctype "NCE Doctype"
"""

from __future__ import unicode_literals

import frappe
from frappe.tests.utils import FrappeTestCase

# ---------------------------------------------------------------------------
#  Helpers — version detection
# ---------------------------------------------------------------------------


def get_frappe_major_version():
    """Return the major version of the installed Frappe framework as an int.

    Centralised here so tests can branch on version when absolutely necessary.
    """
    return int(frappe.__version__.split(".")[0])


def is_v16_or_later():
    """True when running on Frappe v16+."""
    return get_frappe_major_version() >= 16


# ---------------------------------------------------------------------------
#  Helpers — test data factories
# ---------------------------------------------------------------------------


def make_nce_doctype(**kwargs):
    """Create and insert a NCE Doctype document for testing.

    Pass any field as a keyword argument to override the defaults.

    Returns:
        frappe.Document: The newly inserted document.

    Example::

        doc = make_nce_doctype(title="Test Record", status="In Progress")
        assert doc.name
    """
    defaults = {
        "doctype": "NCE Doctype",
        "title": "Test Record",
        "status": "Open",
        "description": "Auto-generated by test suite.",
    }
    defaults.update(kwargs)

    doc = frappe.get_doc(defaults)
    doc.insert(ignore_permissions=True)
    return doc


def cleanup_test_records(doctype="NCE Doctype", filters=None):
    """Delete all test records matching *filters* (or all records of the DocType).

    Useful in ``tearDown`` / ``tearDownClass`` to leave the DB clean.

    Args:
        doctype (str): DocType name to clean up.
        filters (dict | None): Optional Frappe-style filters. If ``None``,
            deletes **all** records of the given DocType — use with care.
    """
    records = frappe.get_all(doctype, filters=filters, pluck="name")
    for name in records:
        frappe.delete_doc(doctype, name, force=True, ignore_permissions=True)
    frappe.db.commit()


# ---------------------------------------------------------------------------
#  Base Test Case
# ---------------------------------------------------------------------------


class NceStudioTestCase(FrappeTestCase):
    """Base class for all NCE Studio tests.

    Extends ``FrappeTestCase`` with app-specific setup/teardown and helpers.
    Subclass this instead of ``FrappeTestCase`` directly so that shared
    fixtures or flags only need to be declared in one place.

    Example::

        class TestNceDoctype(NceStudioTestCase):
            def test_creation(self):
                doc = make_nce_doctype(title="Hello")
                self.assertEqual(doc.title, "Hello")
                self.assertEqual(doc.status, "Open")
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        # Any one-time setup for the entire test class goes here.
        # e.g. create a test user, enable a feature flag, etc.

    @classmethod
    def tearDownClass(cls):
        super().tearDownClass()
        # Any one-time cleanup for the entire test class goes here.

    def setUp(self):
        super().setUp()
        # Runs before each individual test method.

    def tearDown(self):
        super().tearDown()
        # Runs after each individual test method.
        frappe.db.rollback()

    # ------------------------------------------------------------------
    #  Convenience assertions
    # ------------------------------------------------------------------

    def assertDocExists(self, doctype, name, msg=None):
        """Assert that a document with the given name exists."""
        self.assertTrue(
            frappe.db.exists(doctype, name),
            msg or f"{doctype} '{name}' should exist but was not found.",
        )

    def assertDocNotExists(self, doctype, name, msg=None):
        """Assert that a document with the given name does NOT exist."""
        self.assertFalse(
            frappe.db.exists(doctype, name),
            msg or f"{doctype} '{name}' should not exist but was found.",
        )

    def assertDocValue(self, doctype, name, fieldname, expected, msg=None):
        """Assert that a document field has the expected value in the DB."""
        actual = frappe.db.get_value(doctype, name, fieldname)
        self.assertEqual(
            actual,
            expected,
            msg
            or f"{doctype} '{name}'.{fieldname}: expected {expected!r}, got {actual!r}",
        )
